---
abstract: 'Extend Getopt::Long to easily create and maintain command line options'
author:
  - 'Gilbert Healton <gilbert@healton.net>'
build_requires: {}
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Getopt-Object
provides:
  Getopt::Object:
    file: lib/Getopt/Object.pm
    version: 0
  Getopt::ObjectSimple:
    file: lib/Getopt/ObjectSimple.pm
    version: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.004
x_repository:
  type: git
  url: git:/github.com/GilbertsHub/CPAN/Getopt-Object
  web: https://github.com/GilbertsHub/CPAN/Getopt-Object
